name: Publish Python distributions to PyPI and TestPyPI

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    python-build:
        name: Build Python package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Initialize Python 3.9
              uses: actions/setup-python@v1
              with:
                python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --upgrade twine setuptools wheel
                pip install flake8
         
            - name: Lint with flake8
              run: |
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings.
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Install build depndancies
              run: pip install --upgrade twine setuptools wheel

            - name: Build binary wheel and a source tarball
              run: python setup.py sdist bdist_wheel

            - name: Upload distribution package
              uses: actions/upload-artifact@master
              with:
                name: dist-package-3.9
                path: dist

            - name: Download a distribution artifact
              uses: actions/download-artifact@v2
              with:
                name: dist-package-3.9
                path: dist
                
            - name: Publish distribution 📦 to PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                user: __token__
                password: ${{ secrets.pypi_libfinder }}


